### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by m1guelpiedrafita** [nmarulo/softn-cms#1]
Hello!
I am learning pho and searching projects.
Could I help with this?
Contact me at soy@miguelpiedrafita.com
Thanks!
Pad: Sorry for my English, I'm Spanish

**Comment by nmarulo** [comment]
Hola @m1guelpiedrafita , no te preocupes por el ingles yo habla español :+1:

¿En que te puedo ayudar?

También si quieres puedes agregarme a Skype: nmarulo
