### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by AFelipeTrujillo** [nmarulo/softn-cms#3]
Hola, me salio este error, falta una tabla o vista.

`PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'softn_cms.sn_options'`

cuando ejecuto el script de la base de datos me sale este error. 

`Error Code: 1067. Invalid default value for 'comment_date'`

**Comment by nmarulo** [comment]
Hola, bueno como te comente, dime la versión de la base de datos que estas usando.

Yo uso la versión 5.6.25 de MySQL.

**Comment by AFelipeTrujillo** [comment]
@nmarulo yo tengo version 5.5

**Comment by nmarulo** [comment]
@AFelipeTrujillo Te recomiendo, por favor, usar, mínimo, la versión 5.6.25 o MariaBD 10.

Voy a probar, igualmente, que falla en la versión 5.5

**Comment by nmarulo** [comment]
@AFelipeTrujillo Bien, el problema en esa versión (5.5) es que no reconoce "**CURRENT_TIMESTAMP**" puedes buscar en el script "**softn_cms.sql**" las palabras "**DEFAULT CURRENT_TIMESTAMP**" y borrarlas por completo o reemplazar "**CURRENT_TIMESTAMP**" por 0, pero es posible que el rendimiento de la aplicación no sea la adecuada.

**Comment by AFelipeTrujillo** [comment]
Pero queda muy sesgada a los hosting o servidores que ofrecen un versión anterior a MySQL 5.6.

**Comment by nmarulo** [comment]
@AFelipeTrujillo Si, puede que sea cierto.

Lo dejare como un asunto a comprobar e intentare que no tenga problemas con esa versión de MySQL.
